# Generated by Django 2.0.5 on 2021-05-14 04:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('role_type', multiselectfield.db.fields.MultiSelectField(choices=[('pet_owner', 'pet_owner'), ('pet_shelter', 'pet_shelter'), ('general_users', 'general_users'), ('veterinarian', 'veterinarian')], max_length=48)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
